/// <reference types="./types/expect-webdriverio.d.ts"/>

declare namespace jasmine {

    interface Matchers<T> extends WdioMatchers<R, T>{

        /**
         * Below are overloaded Jest's matchers not part of `expect` but of `jest-snapshot`.
         * We need to define them below so that they are correctly typed overloaded
         * @see https://github.com/jestjs/jest/blob/73dbef5d2d3195a1e55fb254c54cce70d3036252/packages/jest-snapshot/src/types.ts#L37
         */

        /**
         * snapshot matcher
         * @param label optional snapshot label
         */
        toMatchSnapshot(label?: string): Promise<R>;

        // TODO - this is not working as expected, need to investigate
        /**
         * snapshot matcher
         * @param label optional snapshot label
         */
        // toMatchSnapshot: T extends WdioElementLike ? (label: string) => Promise<R> : (hint?: string) => R;

        /**
         * inline snapshot matcher
         * @param snapshot snapshot string (autogenerated if not specified)
         * @param label optional snapshot label
         */
        toMatchInlineSnapshot(snapshot?: string, label?: string): Promise<R>
    }

    // type MatcherAndInverse<R, T> = Matchers<R, T>
    // interface AsyncMatchers<T, R> extends WdioMatchers<R, T> {}
}

