// Each member of the global `ExpectWebdriverIO` namespace of v7 is still there
type NsAfterAssertionHookParams = ExpectWebdriverIO.AfterAssertionHookParams
type NsAssertionHookParams = ExpectWebdriverIO.AssertionHookParams
type NsAssertionResult = ExpectWebdriverIO.AssertionResult
type NsAsymmetricMatchers = ExpectWebdriverIO.AsymmetricMatchers
type NsAsyncAssertionResult = ExpectWebdriverIO.AsyncAssertionResult
type NsCommandOptions = ExpectWebdriverIO.CommandOptions
type NsDefaultOptions = ExpectWebdriverIO.DefaultOptions
type NsExpect = ExpectWebdriverIO.Expect
type NsHTMLOptions = ExpectWebdriverIO.HTMLOptions
type NsInverseAsymmetricMatchers = ExpectWebdriverIO.InverseAsymmetricMatchers
type NsJsonCompatible = ExpectWebdriverIO.JsonCompatible
type NsMatcherContext = ExpectWebdriverIO.MatcherContext
type NsMatchers = ExpectWebdriverIO.Matchers<void, unknown>
type NsMatchersAndInverse = ExpectWebdriverIO.MatchersAndInverse<void, unknown>
type NsMultiRemotePartialMatcher = ExpectWebdriverIO.MultiRemotePartialMatcher<unknown>
type NsNumberMatcher = ExpectWebdriverIO.NumberMatcher
type NsOneOfPartialMatcher = ExpectWebdriverIO.OneOfPartialMatcher<unknown>
type NsPartialMatcher = ExpectWebdriverIO.PartialMatcher<unknown>
type NsPartialMatcherAnything = ExpectWebdriverIO.PartialMatcherAnything
type NsPromiseMatchers = ExpectWebdriverIO.PromiseMatchers
type NsRequestedWith = ExpectWebdriverIO.RequestedWith
type NsSnapshotService = typeof ExpectWebdriverIO.SnapshotService
type NsSnapshotServiceArgs = ExpectWebdriverIO.SnapshotServiceArgs
type NsSoftAssertService = typeof ExpectWebdriverIO.SoftAssertService
type NsSoftAssertionService = typeof ExpectWebdriverIO.SoftAssertionService
type NsSoftAssertionServiceOptions = ExpectWebdriverIO.SoftAssertionServiceOptions
type NsSoftFailure = ExpectWebdriverIO.SoftFailure
type NsStringOptions = ExpectWebdriverIO.StringOptions
type NsToBeDisplayedOptions = ExpectWebdriverIO.ToBeDisplayedOptions
type Nsexpect = typeof ExpectWebdriverIO.expect
type NsgetDefaultOptions = typeof ExpectWebdriverIO.getDefaultOptions
type NsjsonArray = ExpectWebdriverIO.jsonArray
type NsjsonObject = ExpectWebdriverIO.jsonObject
type NsjsonPrimitive = ExpectWebdriverIO.jsonPrimitive
type NssetDefaultOptions = typeof ExpectWebdriverIO.setDefaultOptions
type NswdioCustomMatchers = typeof ExpectWebdriverIO.wdioCustomMatchers

export type NamespaceMembers = [NsAfterAssertionHookParams, NsAssertionHookParams, NsAssertionResult, NsAsymmetricMatchers, NsAsyncAssertionResult, NsCommandOptions, NsDefaultOptions, NsExpect, NsHTMLOptions, NsInverseAsymmetricMatchers, NsJsonCompatible, NsMatcherContext, NsMatchers, NsMatchersAndInverse, NsMultiRemotePartialMatcher, NsNumberMatcher, NsOneOfPartialMatcher, NsPartialMatcher, NsPartialMatcherAnything, NsPromiseMatchers, NsRequestedWith, NsSnapshotService, NsSnapshotServiceArgs, NsSoftAssertService, NsSoftAssertionService, NsSoftAssertionServiceOptions, NsSoftFailure, NsStringOptions, NsToBeDisplayedOptions, Nsexpect, NsgetDefaultOptions, NsjsonArray, NsjsonObject, NsjsonPrimitive, NssetDefaultOptions, NswdioCustomMatchers]
