name: E2e Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual trigger from the GitHub UI or CLI

jobs:
  linux:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm ci && npm ci --prefix playgrounds
      - name: Ensure Snapshots
        run: npm run playgrounds:snapshots:update
      - name: Run All Checks
        run: npm run playgrounds:ci:checks:all
